apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: helm-secrets
  namespace: argocd
spec:
  version: v1
  generate:
    command: [sh, -c]
    args:
      - |
        helm secrets template "$ARGOCD_APP_NAME" . \
          --include-crds \
          -n "$ARGOCD_APP_NAMESPACE" \
          -f values.yaml \
          -f values-staging.yaml \
          -f secrets://secrets/staging.yaml.enc
